<?php

namespace ContainerKnpuTPf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBasicAgentCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\BasicAgentCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\BasicAgentCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('basic-agent', [], 'Add a short description for your command', false, #[\Closure(name: 'App\\Command\\BasicAgentCommand')] fn (): \App\Command\BasicAgentCommand => ($container->privates['App\\Command\\BasicAgentCommand'] ?? $container->load('getBasicAgentCommandService')));
    }
}
