<?php

namespace ContainerKnpuTPf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBasicChatCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\BasicChatCommand' shared autowired service.
     *
     * @return \App\Command\BasicChatCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/BasicChatCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Model/Core/Agent/Team.php';
        include_once \dirname(__DIR__, 4).'/src/Model/Core/Agent/MessageContextTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Model/Team/CodingTeam.php';

        $container->privates['App\\Command\\BasicChatCommand'] = $instance = new \App\Command\BasicChatCommand(($container->privates['App\\Model\\Team\\CodingTeam'] ??= new \App\Model\Team\CodingTeam()));

        $instance->setName('basic-chat-agent');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
