<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKnpuTPf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKnpuTPf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKnpuTPf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKnpuTPf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKnpuTPf\App_KernelDevDebugContainer([
    'container.build_hash' => 'KnpuTPf',
    'container.build_id' => '6479e33c',
    'container.build_time' => 1752435913,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKnpuTPf');
